"""
Email Configuration & SMTP Setup
Handles Gmail SMTP connection with retry logic and error handling.
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
from datetime import datetime

# Load environment variables from .env file
load_dotenv()

# Gmail SMTP Configuration
GMAIL_SMTP_SERVER = "smtp.gmail.com"
GMAIL_SMTP_PORT = 587

# Retrieve credentials from environment variables
EMAIL_USER = os.getenv("EMAIL_USER", "")
EMAIL_PASSWORD = os.getenv("EMAIL_PASS", "")
RECIPIENT_EMAIL = os.getenv("RECIPIENT_EMAIL", EMAIL_USER)

# Alert Configuration
TEMPERATURE_THRESHOLD = float(os.getenv("TEMP_THRESHOLD", "50"))  # Default: 50°C
ALERT_COOLDOWN_SECONDS = int(os.getenv("ALERT_COOLDOWN", "3600"))  # 1 hour default


class EmailAlert:
    """
    Handles email alert sending via Gmail SMTP.
    Includes retry logic and proper error handling.
    """

    def __init__(self):
        self.smtp_server = GMAIL_SMTP_SERVER
        self.smtp_port = GMAIL_SMTP_PORT
        self.sender_email = EMAIL_USER
        self.sender_password = EMAIL_PASSWORD
        self.max_retries = 3
        self.retry_delay = 5  # seconds

    def validate_credentials(self) -> bool:
        """
        Validates that email credentials are configured.
        Returns True if valid, False otherwise.
        """
        if not self.sender_email or not self.sender_password:
            print("❌ ERROR: EMAIL_USER or EMAIL_PASS not set in .env")
            return False
        return True

    def create_alert_email(self, temperature: float, humidity: float, 
                          timestamp: str, device_name: str = "ESP32") -> tuple:
        """
        Creates email subject and body for temperature alert.
        
        Args:
            temperature: Current temperature in °C
            humidity: Current humidity in %
            timestamp: ISO format timestamp
            device_name: Name of the device sending the alert
            
        Returns:
            Tuple of (subject, body)
        """
        subject = f"🚨 Temperature Alert: {temperature}°C (Threshold: {TEMPERATURE_THRESHOLD}°C)"
        
        body = f"""
╔══════════════════════════════════════════════════════╗
║         🌡️  CRITICAL TEMPERATURE ALERT  🚨            ║
╚══════════════════════════════════════════════════════╝

⚠️  ALERT DETAILS:
─────────────────────────────────
📊 Current Temperature  : {temperature}°C
🔴 Alert Threshold      : {TEMPERATURE_THRESHOLD}°C
💧 Humidity             : {humidity}%
📍 Device Name          : {device_name}

🕒 Timestamp            : {timestamp}
⏰ Alert Sent At        : {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}

─────────────────────────────────
⚡ ACTION REQUIRED:
• Check the device immediately
• Verify sensor accuracy
• Review environmental conditions
• Check cooling system status

─────────────────────────────────
📝 NOTE: You will receive another alert only after:
   1. Temperature returns to normal (below {TEMPERATURE_THRESHOLD}°C)
   2. Then exceeds the threshold again

This prevents alert spam while keeping you informed.

─────────────────────────────────
Generated by: Real-Time Temperature Monitoring System
Status: PRODUCTION ALERT
═══════════════════════════════════════════════════════
"""
        return subject, body

    def send_email(self, subject: str, body: str, recipient: str = None) -> bool:
        """
        Sends email via Gmail SMTP with retry logic.
        
        Args:
            subject: Email subject line
            body: Email body content
            recipient: Recipient email address (uses RECIPIENT_EMAIL if None)
            
        Returns:
            True if sent successfully, False on failure
        """
        if not self.validate_credentials():
            return False

        recipient = recipient or RECIPIENT_EMAIL
        if not recipient:
            print("❌ ERROR: No recipient email address configured (RECIPIENT_EMAIL or EMAIL_USER)")
            return False

        for attempt in range(1, self.max_retries + 1):
            try:
                print(f"\n📧 Sending email (Attempt {attempt}/{self.max_retries})...")
                
                # Create email message
                msg = MIMEMultipart("alternative")
                msg["Subject"] = subject
                msg["From"] = self.sender_email
                msg["To"] = recipient
                
                # Attach HTML version for better formatting
                html_body = self._convert_to_html(body)
                msg.attach(MIMEText(body, "plain"))
                msg.attach(MIMEText(html_body, "html"))
                
                # Connect and send
                print(f"🔗 Connecting to {self.smtp_server}:{self.smtp_port}...")
                with smtplib.SMTP(self.smtp_server, self.smtp_port, timeout=10) as server:
                    server.starttls()  # Enable TLS encryption
                    print(f"🔐 Authenticating as {self.sender_email}...")
                    server.login(self.sender_email, self.sender_password)
                    
                    print(f"📤 Sending to {recipient}...")
                    server.sendmail(self.sender_email, recipient, msg.as_string())
                
                print(f"✅ Email sent successfully to {recipient}")
                return True
                
            except smtplib.SMTPAuthenticationError as e:
                print(f"❌ Authentication failed: {e}")
                print("   → Check EMAIL_USER and EMAIL_PASS in .env")
                print("   → Use App Password, not regular Gmail password")
                return False
                
            except smtplib.SMTPException as e:
                print(f"❌ SMTP error (Attempt {attempt}): {e}")
                if attempt < self.max_retries:
                    print(f"   Retrying in {self.retry_delay} seconds...")
                    import time
                    time.sleep(self.retry_delay)
                    
            except Exception as e:
                print(f"❌ Unexpected error (Attempt {attempt}): {e}")
                if attempt < self.max_retries:
                    print(f"   Retrying in {self.retry_delay} seconds...")
                    import time
                    time.sleep(self.retry_delay)
        
        print(f"❌ Failed to send email after {self.max_retries} attempts")
        return False

    @staticmethod
    def _convert_to_html(text: str) -> str:
        """
        Converts plain text to HTML for better email formatting.
        """
        html = f"""
        <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <div style="background-color: #f5f5f5; padding: 20px; border-radius: 5px;">
                    <pre style="white-space: pre-wrap; word-wrap: break-word; font-size: 14px;">
{text.strip()}
                    </pre>
                </div>
            </body>
        </html>
        """
        return html


# Global email alert instance
email_alert_service = EmailAlert()
